import { useState, useMemo, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  DndContext,
  type DragEndEvent,
  DragOverlay,
  type DragStartEvent,
  closestCenter,
} from '@dnd-kit/core'
import { scheduleApi } from '@/api/schedule'
import { groupsApi } from '@/api/groups'
import { facultiesApi, fieldsApi, specsApi } from '@/api/faculties'
import { useAcademicYearStore, SEMESTER_TYPE_NUMBERS } from '@/store/academicYearStore'
import { Button } from '@/components/ui/button'
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select'
import type { ScheduleTemplate, ClassType, DayOfWeek, StudyMode } from '@/types'
import {
  CLASS_COLORS, CLASS_LABELS, DAYS_FULL, DAYS_PART,
  END_HOUR, SLOT_HEIGHT, SLOT_MINS, SLOTS, START_MINS,
} from './lib/constants'
import { minsToTime, timeToMins } from './lib/time'
import { getValidSlots, partTimeWindowFrom, weekTypesConflict } from './lib/helpers'
import { DraggableTemplateBlock } from './components/DraggableTemplateBlock'
import { DroppableSlot } from './components/DroppableSlot'
import { TimeColumn } from './components/TimeColumn'
import { GroupCheckboxPicker } from './components/GroupCheckboxPicker'
import { AddTemplateDialog } from './dialogs/AddTemplateDialog'
import { EditTemplateDialog } from './dialogs/EditTemplateDialog'
import { GenerateSemesterDialog } from './dialogs/GenerateSemesterDialog'
import { AutoGenerateDialog } from './dialogs/AutoGenerateDialog'

export function TemplateTab({ academicYear }: { academicYear: string }) {
  const { semesterType } = useAcademicYearStore()
  const availableSemesters = SEMESTER_TYPE_NUMBERS[semesterType]

  const [facultyId, setFacultyId] = useState('')
  const [fieldOfStudyId, setFieldOfStudyId] = useState('')
  const [specializationId, setSpecializationId] = useState('')
  const [semester, setSemester] = useState('')
  const [studyMode, setStudyMode] = useState('')

  const [filterGroupIds, setFilterGroupIds] = useState<Set<string> | null>(null)
  const [filterInstructorId, setFilterInstructorId] = useState('')
  const [filterClassType, setFilterClassType] = useState('')
  const [filterRoomId, setFilterRoomId] = useState('')

  useEffect(() => {
    setFilterInstructorId('')
    setFilterClassType('')
    setFilterRoomId('')
    setFilterGroupIds(null)
  }, [facultyId, fieldOfStudyId, specializationId, semester, studyMode])

  const displayStudyMode: StudyMode = (studyMode as StudyMode) || 'FULL_TIME'
  const days = !studyMode
    ? [...DAYS_FULL, { key: 'SATURDAY' as DayOfWeek, label: 'Sobota' }, { key: 'SUNDAY' as DayOfWeek, label: 'Niedziela' }]
    : studyMode === 'PART_TIME' ? DAYS_PART : DAYS_FULL

  const [addSlot, setAddSlot] = useState<{ dayOfWeek: string; startTime: string } | null>(null)
  const [editTemplate, setEditTemplate] = useState<ScheduleTemplate | null>(null)
  const [showGenerateSemester, setShowGenerateSemester] = useState(false)
  const [showAutoGenerate, setShowAutoGenerate] = useState(false)
  const [activeId, setActiveId] = useState<string | null>(null)
  const [overSlot, setOverSlot] = useState<string | null>(null)

  const { data: facultiesData } = useQuery({
    queryKey: ['faculties'],
    queryFn: () => facultiesApi.getAll(),
  })
  const { data: fieldsData } = useQuery({
    queryKey: ['fields-of-study', facultyId],
    queryFn: () => fieldsApi.getAll(facultyId || undefined),
    enabled: !!studyMode,
  })
  const { data: specsData } = useQuery({
    queryKey: ['specializations', fieldOfStudyId],
    queryFn: () => specsApi.getAll(fieldOfStudyId),
    enabled: !!fieldOfStudyId,
  })
  const { data: groupsData } = useQuery({
    queryKey: ['groups-tmpl', academicYear, fieldOfStudyId, specializationId, semester],
    queryFn: () => groupsApi.getAll({
      academicYear,
      ...(fieldOfStudyId ? { fieldOfStudyId } : {}),
      ...(semester ? { semester: parseInt(semester) } : {}),
    }),
    enabled: !!fieldOfStudyId,
  })

  const faculties = facultiesData?.data.data ?? []
  const fields = fieldsData?.data.data ?? []
  const specs = specsData?.data.data ?? []
  const allGroups = groupsData?.data.data ?? []
  const groups = allGroups.filter(g => {
    const matchesSpec = !specializationId || g.specializationId === specializationId
    const isSN = g.name.includes('-SN-')
    const matchesMode = !studyMode || (studyMode === 'PART_TIME' ? isSN : !isSN)
    return matchesSpec && matchesMode
  })

  const semesterNum = semester ? parseInt(semester) : undefined
  const studyModeVal = (studyMode as StudyMode) || undefined

  const { data, refetch } = useQuery({
    queryKey: ['templates', semesterNum, academicYear, semesterType, studyModeVal],
    queryFn: () => scheduleApi.getTemplates({ semester: semesterNum, semesterType: semesterNum ? undefined : semesterType, academicYear, studyMode: studyModeVal }),
  })

  const { data: allTemplatesData } = useQuery({
    queryKey: ['templates-all', academicYear, semesterType],
    queryFn: () => scheduleApi.getTemplates({ academicYear, semesterType }),
  })

  const templates = data?.data.data ?? []
  const allTemplates = allTemplatesData?.data.data ?? []

  const tmplInstructors = useMemo(() => {
    const seen = new Set<string>()
    const result: Array<{ id: string; firstName: string; lastName: string; title?: string | null }> = []
    for (const t of templates) {
      if (!seen.has(t.instructor.id)) {
        seen.add(t.instructor.id)
        result.push(t.instructor)
      }
    }
    return result.sort((a, b) => a.lastName.localeCompare(b.lastName))
  }, [templates])

  const tmplRooms = useMemo(() => {
    const seen = new Set<string>()
    const result: Array<{ id: string; number: string; building: { name: string } }> = []
    for (const t of templates) {
      if (!seen.has(t.room.id)) {
        seen.add(t.room.id)
        result.push(t.room)
      }
    }
    return result.sort((a, b) => a.number.localeCompare(b.number))
  }, [templates])

  const groupIdSet = useMemo(
    () => fieldOfStudyId ? new Set(groups.map(g => g.id)) : null,
    [fieldOfStudyId, groups]
  )

  const visibleTemplates = useMemo(() =>
    templates.filter(t =>
      (!groupIdSet || !t.studentGroup || groupIdSet.has(t.studentGroup.id)) &&
      (filterGroupIds === null || (t.studentGroup ? filterGroupIds.has(t.studentGroup.id) : false)) &&
      (!filterInstructorId || t.instructor.id === filterInstructorId) &&
      (!filterClassType || t.classType === filterClassType) &&
      (!filterRoomId || t.room.id === filterRoomId)
    ),
    [templates, filterGroupIds, filterInstructorId, filterClassType, filterRoomId, groupIdSet]
  )

  const byDay = useMemo(() => {
    const map: Record<string, ScheduleTemplate[]> = {}
    for (const d of days) map[d.key] = []
    for (const t of templates) {
      if (map[t.dayOfWeek]) map[t.dayOfWeek]!.push(t)
    }
    return map
  }, [templates, days])

  // allByDay: wszystkie szablony roku (do walidacji kolizji, niezależnie od filtrów)
  const allByDay = useMemo(() => {
    const map: Record<string, ScheduleTemplate[]> = {}
    for (const d of [...DAYS_FULL, ...DAYS_PART]) map[d.key] = []
    for (const t of allTemplates) {
      if (map[t.dayOfWeek]) map[t.dayOfWeek]!.push(t)
    }
    return map
  }, [allTemplates])

  const visibleByDay = useMemo(() => {
    const map: Record<string, ScheduleTemplate[]> = {}
    for (const d of days) map[d.key] = []
    for (const t of visibleTemplates) {
      if (map[t.dayOfWeek]) map[t.dayOfWeek]!.push(t)
    }
    return map
  }, [visibleTemplates, days])

  const activeTemplate = activeId ? templates.find(t => t.id === activeId) : null

  const activeGroupFamilyIds = useMemo((): Set<string> => {
    const gid = activeTemplate?.studentGroup?.id
    if (!gid) return new Set()
    const allGroups = allTemplates.flatMap(t => t.studentGroup ? [t.studentGroup] : [])
    const idToParent = new Map(allGroups.map(g => [g.id, g.parentGroupId]))
    const family = new Set<string>([gid])
    let cur: string | null | undefined = idToParent.get(gid)
    while (cur) { family.add(cur); cur = idToParent.get(cur) }
    const queue = [gid]
    while (queue.length > 0) {
      const id = queue.shift()!
      for (const [cid, pid] of idToParent) {
        if (pid === id && !family.has(cid)) { family.add(cid); queue.push(cid) }
      }
    }
    return family
  }, [activeTemplate, allTemplates])

  const dragInfo = useMemo(() => {
    if (!activeTemplate) return null
    const durationMins = timeToMins(activeTemplate.endTime) - timeToMins(activeTemplate.startTime)
    const blockMins = durationMins
    const result: Record<string, Array<{ top: number; height: number }>> = {}
    const groupConflict = (t: ScheduleTemplate) =>
      t.studentGroup?.id != null && activeGroupFamilyIds.has(t.studentGroup.id)
    for (const day of days) {
      if (activeTemplate.studyMode === 'PART_TIME') {
        const windowFrom = partTimeWindowFrom(day.key)
        if (windowFrom === null) { result[day.key] = []; continue }
        const occupied = (allByDay[day.key] ?? [])
          .filter(t =>
            t.id !== activeTemplate.id &&
            weekTypesConflict(activeTemplate.weekType, t.weekType) && (
              t.room.id === activeTemplate.room.id ||
              t.instructor.id === activeTemplate.instructor.id ||
              groupConflict(t)
            )
          )
          .map(t => ({ start: timeToMins(t.startTime), end: timeToMins(t.endTime) }))
        result[day.key] = getValidSlots(occupied, blockMins, durationMins, windowFrom)
        continue
      }
      const occupied = (allByDay[day.key] ?? [])
        .filter(t =>
          t.id !== activeTemplate.id &&
          weekTypesConflict(activeTemplate.weekType, t.weekType) && (
            t.room.id === activeTemplate.room.id ||
            t.instructor.id === activeTemplate.instructor.id ||
            groupConflict(t)
          )
        )
        .map(t => ({ start: timeToMins(t.startTime), end: timeToMins(t.endTime) }))
      result[day.key] = getValidSlots(occupied, blockMins, durationMins)
    }
    return result
  }, [activeTemplate, allByDay, days, activeGroupFamilyIds])

  const hoverGhostTemplate = useMemo(() => {
    if (!activeTemplate || !overSlot) return null
    const [dayKey, slotTime] = overSlot.split('::')
    if (!dayKey || !slotTime) return null
    const startMins = timeToMins(slotTime)
    const durationMins = timeToMins(activeTemplate.endTime) - timeToMins(activeTemplate.startTime)
    const blockMins = durationMins
    if (startMins + blockMins > END_HOUR * 60) return null
    const proposedEnd = startMins + durationMins
    const others = (allByDay[dayKey] ?? []).filter(t =>
      t.id !== activeTemplate.id &&
      weekTypesConflict(activeTemplate.weekType, t.weekType) && (
        t.room.id === activeTemplate.room.id ||
        t.instructor.id === activeTemplate.instructor.id ||
        (t.studentGroup?.id != null && activeGroupFamilyIds.has(t.studentGroup.id))
      )
    )
    const conflicts = others.filter(t => {
      const s = timeToMins(t.startTime), e = timeToMins(t.endTime)
      return s < proposedEnd && e > startMins
    })
    let timeWindowOk = true
    if (activeTemplate.studyMode === 'PART_TIME') {
      const windowFrom = partTimeWindowFrom(dayKey)
      timeWindowOk = windowFrom !== null && startMins >= windowFrom && proposedEnd <= END_HOUR * 60
    }
    const timeWindowViolation = !timeWindowOk
    const valid = conflicts.length === 0 && timeWindowOk
    return { dayKey, startMins, blockMins, valid, conflicts, timeWindowViolation }
  }, [activeTemplate, overSlot, allByDay])

  const qc = useQueryClient()

  const updateMutation = useMutation({
    mutationFn: ({ id, dayOfWeek, startTime, endTime }: { id: string; dayOfWeek: string; startTime: string; endTime: string }) =>
      scheduleApi.updateTemplate(id, { dayOfWeek, startTime, endTime }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['templates'] })
      qc.invalidateQueries({ queryKey: ['templates-all'] })
    },
    onError: () => {
      qc.invalidateQueries({ queryKey: ['templates-all'] })
    },
  })

  const deleteManyMutation = useMutation({
    mutationFn: () => scheduleApi.deleteTemplates({ semester: semesterNum, academicYear, studyMode: studyModeVal }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['templates'] })
      qc.invalidateQueries({ queryKey: ['templates-all'] })
    },
  })

  function handleDragStart(e: DragStartEvent) {
    setActiveId(String(e.active.id))
  }

  function handleDragEnd(e: DragEndEvent) {
    setActiveId(null)
    setOverSlot(null)
    const { over, active } = e
    if (!over) return

    const [day, slotTime] = String(over.id).split('::')
    if (!day || !slotTime) return

    const tpl = templates.find(t => t.id === active.id)
    if (!tpl) return

    const startMins = timeToMins(slotTime)
    const durationMins = timeToMins(tpl.endTime) - timeToMins(tpl.startTime)
    const endMins = startMins + durationMins
    const newStart = minsToTime(startMins)
    const newEnd = minsToTime(endMins)

    if (tpl.dayOfWeek === day && tpl.startTime === newStart) return

    if (tpl.studyMode === 'PART_TIME') {
      const windowFrom = partTimeWindowFrom(day)
      if (windowFrom === null || startMins < windowFrom || endMins > END_HOUR * 60) return
    }

    const others = (allByDay[day] ?? []).filter(t =>
      t.id !== tpl.id &&
      weekTypesConflict(tpl.weekType, t.weekType) && (
        t.room.id === tpl.room.id ||
        t.instructor.id === tpl.instructor.id ||
        (t.studentGroup?.id && t.studentGroup.id === tpl.studentGroup?.id)
      )
    )
    const hasConflict = others.some(t => {
      const s = timeToMins(t.startTime), e2 = timeToMins(t.endTime)
      return s < endMins && e2 > startMins
    })
    if (hasConflict) return

    updateMutation.mutate({ id: tpl.id, dayOfWeek: day, startTime: newStart, endTime: newEnd })
  }

  const totalSlotsHeight = SLOTS.length * SLOT_HEIGHT

  return (
    <div>
      {/* Sekcja 1: Zakres generowania planu */}
      <div className="p-3 mb-2 bg-card rounded-lg border border-border">
        <p className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wide mb-2">Zakres generowania planu i widok</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Wydział</label>
            <Select value={facultyId || '__all__'} onValueChange={v => {
              const val = v === '__all__' ? '' : v
              setFacultyId(val); setStudyMode(''); setFieldOfStudyId(''); setSpecializationId(''); setSemester(''); setFilterGroupIds(null)
            }}>
              <SelectTrigger className="w-full h-8 text-xs"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie wydziały</SelectItem>
                {faculties.map(f => <SelectItem key={f.id} value={f.id}>{f.shortName}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Tryb</label>
            <Select value={studyMode || '__all__'} onValueChange={v => {
              setStudyMode(v === '__all__' ? '' : v)
              setFieldOfStudyId(''); setSpecializationId(''); setSemester(''); setFilterGroupIds(null)
            }} disabled={!facultyId}>
              <SelectTrigger className="w-full h-8 text-xs">
                <SelectValue placeholder="—" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie tryby</SelectItem>
                <SelectItem value="FULL_TIME">Stacjonarne</SelectItem>
                <SelectItem value="PART_TIME">Niestacjonarne</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Kierunek</label>
            <Select value={fieldOfStudyId || '__all__'} onValueChange={v => {
              const val = v === '__all__' ? '' : v
              setFieldOfStudyId(val); setSpecializationId(''); setSemester(''); setFilterGroupIds(null)
            }} disabled={!studyMode}>
              <SelectTrigger className="w-full h-8 text-xs">
                <SelectValue placeholder="—" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie kierunki</SelectItem>
                {fields.map(f => <SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Specjalność</label>
            <Select value={specializationId || '__all__'} onValueChange={v => {
              const val = v === '__all__' ? '' : v
              setSpecializationId(val); setFilterGroupIds(null)
            }} disabled={!fieldOfStudyId}>
              <SelectTrigger className="w-full h-8 text-xs">
                <SelectValue placeholder="—" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie specjalności</SelectItem>
                {specs.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Semestr</label>
            <Select value={semester || '__all__'} onValueChange={v => setSemester(v === '__all__' ? '' : v)} disabled={!specializationId}>
              <SelectTrigger className="w-full h-8 text-xs">
                <SelectValue placeholder="—" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie semestry</SelectItem>
                {availableSemesters.map(s => (
                  <SelectItem key={s} value={String(s)}>Sem. {s}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">
              Grupy {filterGroupIds !== null && <span className="text-primary font-semibold">({filterGroupIds.size})</span>}
            </label>
            <GroupCheckboxPicker
              groups={groups}
              selected={filterGroupIds}
              onChange={setFilterGroupIds}
              disabled={!specializationId}
            />
          </div>

        </div>

        {(facultyId || studyMode || fieldOfStudyId || specializationId || semester || filterGroupIds !== null) && (
          <div className="mt-2">
            <Button variant="outline" size="sm" className="h-7 text-xs px-3"
              onClick={() => {
                setFacultyId(''); setStudyMode(''); setFieldOfStudyId(''); setSpecializationId(''); setSemester(''); setFilterGroupIds(null)
              }}>
              Wyczyść filtry
            </Button>
          </div>
        )}

        <div className="flex flex-wrap gap-2 mt-3 pt-3 border-t border-border">
          <Button variant="default" size="sm" onClick={() => setShowAutoGenerate(true)} disabled={!facultyId}>
            Auto-generuj
          </Button>
          <Button variant="outline" size="sm" onClick={() => setShowGenerateSemester(true)} disabled={templates.length === 0}>
            Generuj terminy ({visibleTemplates.length})
          </Button>
          <Button
            variant="destructive" size="sm"
            disabled={deleteManyMutation.isPending || templates.length === 0}
            onClick={() => {
              if (confirm(`Usunąć wzorce dla ${semesterNum ? `sem. ${semesterNum}` : 'wszystkich semestrów'} (${academicYear})?`)) {
                deleteManyMutation.mutate()
              }
            }}
          >
            {deleteManyMutation.isPending ? 'Usuwanie...' : `Wyczyść wzorzec (${templates.length})`}
          </Button>
        </div>
      </div>

      {/* Sekcja 2: Widok (filtry client-side) */}
      <div className="p-3 mb-3 bg-card rounded-lg border border-border">
        <p className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wide mb-2">Widok</p>
        <div className="flex flex-wrap gap-2 items-end">
          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Typ zajęć</label>
            <Select value={filterClassType || '__all__'} onValueChange={v => setFilterClassType(v === '__all__' ? '' : v)}>
              <SelectTrigger className="w-36 h-8 text-xs"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie typy</SelectItem>
                <SelectItem value="LECTURE">Wykład</SelectItem>
                <SelectItem value="EXERCISE">Ćwiczenia</SelectItem>
                <SelectItem value="LAB">Laboratorium</SelectItem>
                <SelectItem value="PROJECT">Projekt</SelectItem>
                <SelectItem value="SEMINAR">Seminarium</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Prowadzący</label>
            <Select value={filterInstructorId || '__all__'} onValueChange={v => setFilterInstructorId(v === '__all__' ? '' : v)}>
              <SelectTrigger className="w-48 h-8 text-xs"><SelectValue placeholder="Wszyscy" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszyscy prowadzący</SelectItem>
                {tmplInstructors.map(i => (
                  <SelectItem key={i.id} value={i.id}>{i.title ? `${i.title} ` : ''}{i.firstName} {i.lastName}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[11px] text-muted-foreground">Sala</label>
            <Select value={filterRoomId || '__all__'} onValueChange={v => setFilterRoomId(v === '__all__' ? '' : v)}>
              <SelectTrigger className="w-36 h-8 text-xs"><SelectValue placeholder="Wszystkie" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">Wszystkie sale</SelectItem>
                {tmplRooms.map(r => (
                  <SelectItem key={r.id} value={r.id}>{r.number} ({r.building.name})</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {(filterClassType || filterInstructorId || filterRoomId) && (
            <div className="flex flex-col justify-end gap-1">
              <label className="text-[11px] text-transparent select-none">_</label>
              <Button variant="outline" size="sm" className="h-8 text-xs px-3"
                onClick={() => { setFilterClassType(''); setFilterInstructorId(''); setFilterRoomId('') }}>
                Wyczyść · {visibleTemplates.length}/{templates.length}
              </Button>
            </div>
          )}
        </div>
      </div>

      <DndContext
        collisionDetection={closestCenter}
        onDragStart={handleDragStart}
        onDragOver={(e) => setOverSlot(e.over ? String(e.over.id) : null)}
        onDragEnd={handleDragEnd}
      >
        <div className="bg-card rounded-lg border border-border overflow-auto">
          <div className="flex min-w-[700px]">
            <TimeColumn />
            {days.map((day) => (
              <div key={day.key} className="flex-1 border-r border-border last:border-r-0">
                <div className="h-10 border-b border-border flex items-center justify-center text-sm font-medium">
                  {day.label}
                </div>
                <div style={{ height: totalSlotsHeight }} className="relative">
                  {SLOTS.map((slot, i) => (
                    <DroppableSlot
                      key={slot}
                      id={`${day.key}::${slot}`}
                      top={i * SLOT_HEIGHT}
                    >
                      <div
                        onClick={() => !activeId && setAddSlot({ dayOfWeek: day.key, startTime: slot })}
                        className={`w-full h-full border-t cursor-pointer hover:bg-primary/5 transition-colors ${
                          i === 0 ? 'border-transparent' :
                          slot.endsWith(':00') ? 'border-border' :
                          slot.endsWith(':30') ? 'border-border/50' :
                          'border-border/20'
                        }`}
                      />
                    </DroppableSlot>
                  ))}
                  {dragInfo?.[day.key]?.map(({ top, height }, i) => (
                    <div key={`v${i}`} style={{ position: 'absolute', top, height, left: 3, right: 3, zIndex: 0 }}
                      className="rounded border border-dashed border-green-500/50 pointer-events-none" />
                  ))}
                  {hoverGhostTemplate?.dayKey === day.key && (
                    <>
                      <div style={{
                        position: 'absolute',
                        top: (hoverGhostTemplate.startMins - START_MINS) / SLOT_MINS * SLOT_HEIGHT,
                        height: hoverGhostTemplate.blockMins / SLOT_MINS * SLOT_HEIGHT - 2,
                        left: 4, right: 4, zIndex: 5,
                      }}
                        className={`rounded border-2 pointer-events-none ${
                          hoverGhostTemplate.valid
                            ? 'bg-green-500/30 border-green-400'
                            : 'bg-red-500/25 border-red-400'
                        }`}
                      />
                      {!hoverGhostTemplate.valid && (
                        <div style={{
                          position: 'absolute',
                          top: (hoverGhostTemplate.startMins - START_MINS) / SLOT_MINS * SLOT_HEIGHT,
                          left: 4, right: 4, zIndex: 6,
                        }}
                          className="pointer-events-none bg-red-950/95 rounded border border-red-500 px-1.5 py-1"
                        >
                          {hoverGhostTemplate.timeWindowViolation ? (
                            <>
                              <p className="text-[10px] font-bold text-red-300 uppercase tracking-wide mb-1">
                                Poza oknem czasowym
                              </p>
                              <p className="text-[9px] text-red-300 leading-tight">
                                Niestacjonarne: Pt 15:00–20:00
                              </p>
                              <p className="text-[9px] text-red-300 leading-tight">
                                Sb/Nd 07:00–20:00
                              </p>
                            </>
                          ) : hoverGhostTemplate.conflicts.length > 0 && (
                            <>
                              <p className="text-[10px] font-bold text-red-300 uppercase tracking-wide mb-1">
                                Kolizja ({hoverGhostTemplate.conflicts.length})
                              </p>
                              {hoverGhostTemplate.conflicts.map((t, i) => {
                                const reasons = [
                                  t.room.id === activeTemplate!.room.id && `sala ${t.room.number}`,
                                  t.instructor.id === activeTemplate!.instructor.id && `${t.instructor.title ? t.instructor.title + ' ' : ''}${t.instructor.lastName}`,
                                  t.studentGroup?.id && activeGroupFamilyIds.has(t.studentGroup.id) && `gr. ${t.studentGroup.name}`,
                                ].filter(Boolean).join(', ')
                                return (
                                  <div key={i} className="mb-1 last:mb-0 border-l-2 border-red-400 pl-1.5">
                                    <p className="text-[10px] font-semibold text-red-100 leading-tight">
                                      {t.curriculumEntry.subject.name}
                                    </p>
                                    <p className="text-[9px] text-red-300 leading-tight">
                                      {t.startTime}–{t.endTime}
                                    </p>
                                    <p className="text-[9px] text-orange-300 leading-tight font-medium">
                                      ↳ {reasons}
                                    </p>
                                  </div>
                                )
                              })}
                            </>
                          )}
                        </div>
                      )}
                    </>
                  )}
                  {visibleByDay[day.key]?.map(t => (
                    <DraggableTemplateBlock
                      key={t.id}
                      template={t}
                      onClick={() => setEditTemplate(t)}
                    />
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        <DragOverlay>
          {activeTemplate && (
            <div
              style={{ height: (timeToMins(activeTemplate.endTime) - timeToMins(activeTemplate.startTime)) / SLOT_MINS * SLOT_HEIGHT - 2 }}
              className={`rounded border-l-4 px-2 py-1 text-xs shadow-xl w-32 ${CLASS_COLORS[activeTemplate.classType as ClassType]}`}
            >
              <p className="font-semibold truncate">{activeTemplate.curriculumEntry.subject.name}</p>
              <p className="truncate opacity-70">{CLASS_LABELS[activeTemplate.classType as ClassType]} · {activeTemplate.room.number}</p>
            </div>
          )}
        </DragOverlay>
      </DndContext>

      <p className="text-xs text-muted-foreground mt-2">
        Kliknij na pustą komórkę aby dodać zajęcia. Przeciągnij blok aby zmienić czas/dzień.
      </p>

      {addSlot && (
        <AddTemplateDialog
          open
          prefill={addSlot}
          semester={semesterNum ?? 1}
          academicYear={academicYear}
          studyMode={displayStudyMode}
          onClose={() => setAddSlot(null)}
          onSuccess={() => void refetch()}
        />
      )}

      {editTemplate && (
        <EditTemplateDialog
          template={editTemplate}
          onClose={() => setEditTemplate(null)}
          onSuccess={() => void refetch()}
        />
      )}

      {showGenerateSemester && (
        <GenerateSemesterDialog
          open
          templates={visibleTemplates}
          academicYear={academicYear}
          semesterType={semesterType}
          onClose={() => setShowGenerateSemester(false)}
        />
      )}

      <AutoGenerateDialog
        open={showAutoGenerate}
        onClose={() => setShowAutoGenerate(false)}
        semester={semesterNum}
        semesterType={semesterType}
        academicYear={academicYear}
        studyMode={studyModeVal}
        facultyId={facultyId || undefined}
        fieldOfStudyId={fieldOfStudyId || undefined}
        specializationId={specializationId || undefined}
      />
    </div>
  )
}
