import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { ChevronDown } from 'lucide-react'
import { scheduleApi } from '@/api/schedule'
import { SEMESTER_TYPE_NUMBERS } from '@/store/academicYearStore'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog'
import type { ClassType, DayOfWeek, StudyMode } from '@/types'
import { CLASS_FULL_LABELS, CLASS_LABELS, DAY_SHORT } from '../lib/constants'
import { formatApiError } from '../lib/errors'

type TemplateProposal = {
  specializationId?: string
  specializationName?: string
  curriculumEntryId: string
  subjectName: string
  classType: ClassType
  academicHours: number
  dayOfWeek?: DayOfWeek
  startTime?: string
  endTime?: string
  roomId?: string
  roomNumber?: string
  buildingName?: string
  instructorId?: string | null
  instructorName?: string | null
  studentGroupId?: string | null
  studentGroupName?: string | null
  semester: number
  academicYear: string
  studyMode: StudyMode
  weekType?: string
  warning?: string
  note?: string
  alreadyScheduled?: boolean
}

export function AutoGenerateDialog({
  open, onClose, semester, semesterType, academicYear, studyMode, facultyId, fieldOfStudyId, specializationId,
}: {
  open: boolean
  onClose: () => void
  semester?: number
  semesterType: 'WINTER' | 'SUMMER'
  academicYear: string
  studyMode?: StudyMode
  facultyId?: string
  fieldOfStudyId?: string
  specializationId?: string
}) {
  const [proposals, setProposals] = useState<TemplateProposal[]>([])
  const [selected, setSelected] = useState<Set<number>>(new Set())
  const [step, setStep] = useState<'confirm' | 'preview'>('confirm')

  const qc = useQueryClient()

  const generateMutation = useMutation({
    mutationFn: () => scheduleApi.generateTemplate({
      facultyId: facultyId || undefined,
      fieldOfStudyId: fieldOfStudyId || undefined,
      specializationId: specializationId || undefined,
      semester: semester || undefined,
      semesterType,
      academicYear,
      studyMode: studyMode || undefined,
    }),
    onSuccess: (res) => {
      const data = res.data.data as TemplateProposal[]
      setProposals(data)
      setSelected(new Set(
        data.map((p, i) => (!p.warning && !p.alreadyScheduled) ? i : -1).filter(i => i >= 0)
      ))
      setStep('preview')
    },
  })

  const [savedCount, setSavedCount] = useState(0)
  const [skippedNoInstructor, setSkippedNoInstructor] = useState(0)

  const [saveFailures, setSaveFailures] = useState<string[]>([])

  const saveMutation = useMutation({
    mutationFn: async () => {
      const toSave = proposals.filter((p, i) => selected.has(i) && !p.warning)
      let saved = 0
      let skipped = 0
      const failures: string[] = []
      for (const p of toSave) {
        if (!p.instructorId) { skipped++; continue }
        try {
          await scheduleApi.createTemplate({
            curriculumEntryId: p.curriculumEntryId,
            classType: p.classType,
            academicHours: p.academicHours,
            roomId: p.roomId!,
            instructorId: p.instructorId,
            dayOfWeek: p.dayOfWeek!,
            startTime: p.startTime!,
            endTime: p.endTime!,
            semester: p.semester,
            academicYear: p.academicYear,
            weekType: p.weekType ?? 'EVERY',
            studyMode: p.studyMode,
            studentGroupId: p.studentGroupId ?? undefined,
          })
          saved++
        } catch (err: unknown) {
          const errData = (err as { response?: { data?: { error?: string; details?: Record<string, unknown> } } })?.response?.data
          const errMsg = errData?.error ? formatApiError(errData.error, errData.details) : 'Błąd zapisu'
          const dayLabel = p.dayOfWeek ? (DAY_SHORT[p.dayOfWeek] ?? p.dayOfWeek) : ''
          failures.push(`${p.subjectName} (${CLASS_FULL_LABELS[p.classType] ?? p.classType}) ${dayLabel} ${p.startTime} — ${errMsg}`)
        }
      }
      setSavedCount(saved)
      setSkippedNoInstructor(skipped)
      setSaveFailures(failures)
      qc.invalidateQueries({ queryKey: ['templates'] })
      qc.invalidateQueries({ queryKey: ['templates-all'] })
      if (failures.length === 0 && skipped === 0) handleClose()
    },
  })

  function handleClose() {
    setStep('confirm')
    setProposals([])
    setSelected(new Set())
    setSavedCount(0)
    setSkippedNoInstructor(0)
    setSaveFailures([])
    saveMutation.reset()
    onClose()
  }

  const newIndices  = proposals.map((p, i) => (!p.warning && !p.alreadyScheduled) ? i : -1).filter(i => i >= 0)
  const [showAlreadyScheduled, setShowAlreadyScheduled] = useState(false)

  function toggleAll() {
    setSelected(selected.size === newIndices.length ? new Set() : new Set(newIndices))
  }

  const DAY_LABELS: Partial<Record<DayOfWeek, string>> = {
    MONDAY: 'Pon', TUESDAY: 'Wt', WEDNESDAY: 'Śr', THURSDAY: 'Czw',
    FRIDAY: 'Pt', SATURDAY: 'Sb', SUNDAY: 'Nd',
  }

  const newProposals = proposals.filter(p => !p.alreadyScheduled)
  const alreadyScheduledProposals = proposals.filter(p => p.alreadyScheduled)

  function renderProposalRow(p: TemplateProposal, i: number) {
    const hasSlot = !p.warning
    const hasInstructor = !!p.instructorId
    return (
      <div key={i} className={`flex items-start gap-3 px-3 py-2 ${!hasSlot ? 'opacity-50 bg-muted/30' : ''}`}>
        <input
          type="checkbox"
          className="mt-0.5 cursor-pointer"
          checked={selected.has(i)}
          disabled={!hasSlot}
          onChange={() => setSelected(prev => {
            const next = new Set(prev)
            next.has(i) ? next.delete(i) : next.add(i)
            return next
          })}
        />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium">{p.subjectName}</span>
            <Badge variant="outline" className="text-[10px]">{CLASS_LABELS[p.classType]}</Badge>
            <span className="text-xs text-muted-foreground">{p.academicHours}h</span>
            {p.specializationName && (
              <Badge variant="secondary" className="text-[10px]">{p.specializationName}</Badge>
            )}
          </div>
          {hasSlot ? (
            <div className="text-xs text-muted-foreground mt-0.5">
              {DAY_LABELS[p.dayOfWeek!]} {p.startTime}–{p.endTime} · sala {p.roomNumber} ({p.buildingName})
              {p.instructorName && <span> · {p.instructorName}</span>}
              {p.studentGroupName && <span> · gr. {p.studentGroupName}</span>}
              {(!semester || !studyMode) && (
                <span className="ml-1">
                  {!semester && <span>· sem. {p.semester}</span>}
                  {!studyMode && <span className="ml-1">· {p.studyMode === 'FULL_TIME' ? 'St.' : 'Nst.'}</span>}
                </span>
              )}
              {!hasInstructor && (
                <span className="block text-yellow-600 dark:text-yellow-400 mt-0.5">Brak prowadzącego — wpis zostanie pominięty przy zapisie</span>
              )}
              {p.note && (
                <span className="block text-yellow-600 dark:text-yellow-400 mt-0.5">{p.note}</span>
              )}
            </div>
          ) : (
            <div className="text-xs text-destructive mt-0.5">{p.warning}</div>
          )}
        </div>
      </div>
    )
  }

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) handleClose() }}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Auto-generuj wzorzec tygodnia</DialogTitle>
        </DialogHeader>

        {step === 'confirm' && (
          <div className="space-y-3 py-2">
            <p className="text-sm text-muted-foreground">
              Generator dobierze wolne sloty czasowe, sale i prowadzących na podstawie siatki godzin.
            </p>
            <div className="rounded-md border p-3 text-sm space-y-1 bg-muted/30">
              <div><span className="text-muted-foreground">Semestr:</span> <strong>{semester ?? `${semesterType === 'WINTER' ? 'zimowe' : 'letnie'} (${SEMESTER_TYPE_NUMBERS[semesterType].join(', ')})`}</strong></div>
              <div><span className="text-muted-foreground">Rok akademicki:</span> <strong>{academicYear}</strong></div>
              <div>
                <span className="text-muted-foreground">Tryb: </span>
                <strong>{studyMode ? (studyMode === 'FULL_TIME' ? 'stacjonarne' : 'niestacjonarne') : <span className="text-muted-foreground italic">wszystkie</span>}</strong>
              </div>
              <div>
                <span className="text-muted-foreground">Zakres: </span>
                <strong>
                  {specializationId ? 'wybrana specjalność'
                    : fieldOfStudyId ? 'wszystkie specjalności kierunku'
                    : facultyId ? 'wszystkie specjalności wydziału'
                    : <span className="text-destructive">wybierz co najmniej wydział</span>}
                </strong>
              </div>
            </div>
            {generateMutation.isError && (
              <p className="text-sm text-destructive">
                {(generateMutation.error as { response?: { data?: { error?: string } } })?.response?.data?.error ?? 'Błąd generowania — brak grup lub siatki godzin'}
              </p>
            )}
          </div>
        )}

        {step === 'preview' && (
          <div className="space-y-3 py-2">
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">
                {newProposals.length} nowych propozycji · {selected.size} zaznaczonych
              </p>
              <Button variant="ghost" size="sm" onClick={toggleAll}>
                {selected.size === newIndices.length && newIndices.length > 0 ? 'Odznacz wszystkie' : 'Zaznacz wszystkie'}
              </Button>
            </div>

            <div className="border rounded-md divide-y text-sm">
              {newProposals.map((p) => renderProposalRow(p, proposals.indexOf(p)))}
              {newProposals.length === 0 && (
                <p className="px-3 py-4 text-sm text-muted-foreground text-center">
                  Wszystkie zajęcia z siatki są już zaplanowane.
                </p>
              )}
            </div>

            {alreadyScheduledProposals.length > 0 && (
              <div>
                <button
                  className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1 py-1"
                  onClick={() => setShowAlreadyScheduled(v => !v)}
                >
                  <ChevronDown className={`h-3 w-3 transition-transform ${showAlreadyScheduled ? 'rotate-180' : ''}`} />
                  Już w planie ({alreadyScheduledProposals.length}) — pokaż alternatywne sloty
                </button>
                {showAlreadyScheduled && (
                  <div className="border rounded-md divide-y text-sm opacity-60">
                    {alreadyScheduledProposals.map((p) => renderProposalRow(p, proposals.indexOf(p)))}
                  </div>
                )}
              </div>
            )}


            {saveMutation.isSuccess && savedCount > 0 && saveFailures.length === 0 && skippedNoInstructor === 0 && (
              <p className="text-sm text-green-600">Zapisano {savedCount} wzorców.</p>
            )}
            {skippedNoInstructor > 0 && (
              <p className="text-sm text-yellow-600 dark:text-yellow-400">
                Pominięto {skippedNoInstructor} wpisów bez prowadzącego.
              </p>
            )}
            {saveFailures.length > 0 && (
              <div className="text-sm space-y-0.5">
                <p className="font-medium text-yellow-600 dark:text-yellow-400">
                  Zapisano {savedCount} wzorców, nie zapisano {saveFailures.length} (konflikty):
                </p>
                <div className="max-h-40 overflow-y-auto rounded border border-yellow-500/30 bg-yellow-500/5 px-2 py-1 space-y-0.5">
                  {saveFailures.map((f, i) => <p key={i} className="text-xs text-muted-foreground">{f}</p>)}
                </div>
              </div>
            )}
          </div>
        )}

        <DialogFooter>
          {step === 'confirm' ? (
            <>
              <Button variant="ghost" onClick={handleClose}>Anuluj</Button>
              <Button
                onClick={() => generateMutation.mutate()}
                disabled={(!facultyId && !fieldOfStudyId && !specializationId) || generateMutation.isPending}
              >
                {generateMutation.isPending ? 'Generowanie...' : 'Generuj propozycje'}
              </Button>
            </>
          ) : (
            <>
              {!saveMutation.isSuccess && saveFailures.length === 0 && (
                <Button variant="ghost" onClick={() => setStep('confirm')}>← Wróć</Button>
              )}
              {saveMutation.isSuccess || saveFailures.length > 0 ? (
                <Button onClick={handleClose}>Zamknij</Button>
              ) : (
                <Button
                  onClick={() => saveMutation.mutate()}
                  disabled={selected.size === 0 || saveMutation.isPending}
                >
                  {saveMutation.isPending ? 'Zapisywanie...' : `Zatwierdź zaznaczone (${selected.size})`}
                </Button>
              )}
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
